#!/bin/bash

#<------------------- [ Variables ] ---------------------->

loc="/tmp/webpage"
tmp="/tmp/.deleteitifyouwant"
tag="https://vid.puffyan.us/search?q="

#<------------------------------------------------------->


function Video_0_1 {
if [ -v $video ]; then
    echo "Failed"
    echo "$video"
    rm $loc
else
    mpv $link
    rm $loc $tmp
fi
}

function Audio_0_1 {
if [ -v $video ]; then
    echo "Failed"
    echo "$video"
    rm $loc
else
    mpv --vo=null --video=no --no-video --term-osd-bar --no-resume-playback $link
    rm $loc $tmp
fi
}

disp_check="$(ps -e | grep X | wc -l)"

function ytcli_Video {
if 
	[[ "$disp_check" = "1" ]]; then

	echo "Youtube-CLI"
	search="$(echo "                                     " | dmenu)"
	noplus="$(sed 's/ /+/g' <<< "$search")"
	curl "$tag$noplus" > $loc
	video="$(cat $loc | grep -i '<p dir="auto">' | cut -d '>' -f 2 | sed 's/<\/p//g' | dmenu)"
	echo "$video" > /tmp/.deleteitifyouwant
	link="$(cat $loc | grep -iA11 -F -f $tmp | grep -i "watch on youtube" | cut -d '"' -f 4)"
	Video_0_1

elif 
	[[ "$disp_check" = "0" ]]; then

	echo "Youtube-CLI"
	read -p 'Search: ' search
	noplus="$(sed 's/ /+/g' <<< "$search")"
	curl "$tag$noplus" > $loc
	video="$(cat $loc | grep -i '<p dir="auto">' | cut -d '>' -f 2 | sed 's/<\/p//g' | fzf)"
	echo "$video" > /tmp/.deleteitifyouwant
	link="$(cat $loc | grep -iA11 -F -f $tmp | grep -i "watch on youtube" | cut -d '"' -f 4)"
	Video_0_1
fi
}

function ytcli_Audio {
if 
	[[ "$disp_check" = "1" ]]; then

	echo "Youtube-CLI"
	search="$(echo "                                     " | dmenu)"
	noplus="$(sed 's/ /+/g' <<< "$search")"
	curl "$tag$noplus" > $loc
	video="$(cat $loc | grep -i '<p dir="auto">' | cut -d '>' -f 2 | sed 's/<\/p//g' | dmenu)"
	echo "$video" > /tmp/.deleteitifyouwant
	link="$(cat $loc | grep -iA11 -F -f $tmp | grep -i "watch on youtube" | cut -d '"' -f 4)"
	Audio_0_1
elif
	[[ "$disp_check" = "0" ]]; then

	echo "Youtube-CLI"
	read -p 'Search: ' search
	noplus="$(sed 's/ /+/g' <<< "$search")"
	curl "$tag$noplus" > $loc
	video="$(cat $loc | grep -i '<p dir="auto">' | cut -d '>' -f 2 | sed 's/<\/p//g' | fzf)"
	echo "$video" > /tmp/.deleteitifyouwant
	link="$(cat $loc | grep -iA11 -F -f $tmp | grep -i "watch on youtube" | cut -d '"' -f 4)"
fi
}

function help_ {
    echo "Usage: ytcli [OPTION]"
    echo "-h, Shows this help panel"
    echo "-a, Only plays audio"
    echo "    If no arguments is given then it will output Video"
}

if 
    [ "$1" = "-a" ];
then
    ytcli_Audio; echo
elif 
    [ "$1" = "-h" ];
then
    help_; echo
else
    ytcli_Video; echo
fi
